sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t parthodasyahoocom/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parthodasyahoocom/docker-react npm run test 
